In [5]:
# svd就是奇异值分解，提取信息用的，和pca一样都是工具
# 用于推荐系统和图像压缩
# 缺点是数据的转换可能难以理解，适合数值型数据
# 这个其实就是矩阵分解，分解成三个小的矩阵
# 提取对角元素，也就是奇异值，想想pca也是分解之后提取特征值

In [6]:
from numpy import *
U,Sigma,VT=linalg.svd([[1, 1], [7, 7]])
# 这个linalg是一个线性代数箱
print(U)
print(Sigma)
# 可以发现这个sigma是以行向量的形式返回对角元素，而不是2乘2的矩阵
# 10，0
# 0， 0
# 这种矩阵除了对角元素其他的都是0，就可以节省空间
print(VT)


[[-0.14142136 -0.98994949]
 [-0.98994949  0.14142136]]
[10.  0.]
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]


In [8]:
U,Sigma,VT=linalg.svd([[0, 0, 0, 2, 2],
            [0, 0, 0, 3, 3],
            [0, 0, 0, 1, 1],
            [1, 1, 1, 0, 0],
            [2, 2, 2, 0, 0],
            [5, 5, 5, 0, 0],
            [1, 1, 1, 0, 0]])
print(Sigma)

[9.64365076e+00 5.29150262e+00 7.40623935e-16 4.05103551e-16
 2.21838243e-32]


In [10]:
# 可以看出来前三个数值很大，这样子的话就可以把后面两个给去掉了
Sig3 = mat([[Sigma[0], 0 ,0], [0, Sigma[1], 0], [0, 0, Sigma[2]]])
U[:,:3]*Sig3*VT[:3, :]

matrix([[ 5.03302006e-17,  1.95279569e-15,  1.70575023e-15,
          2.00000000e+00,  2.00000000e+00],
        [-7.69233911e-16,  3.14619452e-16,  4.54614459e-16,
          3.00000000e+00,  3.00000000e+00],
        [-2.02143152e-16,  6.40186235e-17,  1.38124528e-16,
          1.00000000e+00,  1.00000000e+00],
        [ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         -1.52065993e-33, -1.21652794e-33],
        [ 2.00000000e+00,  2.00000000e+00,  2.00000000e+00,
         -3.04131986e-33, -2.43305589e-33],
        [ 5.00000000e+00,  5.00000000e+00,  5.00000000e+00,
          1.82479192e-33,  1.45983353e-33],
        [ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         -1.52065993e-33, -1.21652794e-33]])

In [ ]:
# 能发现和前面给的初始的矩阵差不多
