In [1]:
import numpy as np

my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [3]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 41.9 ms


In [4]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 1.18 s


In [ ]:
# 可以看出来这个np同样用list所消耗的时间比直接用list要少很多

In [5]:
# 多维数组是ndarray
data = np.random.randn(2, 3)
# 生成二行三列的随机的数组
print(data)




[[-1.30878156 -0.36379112 -1.49660942]
 [-0.99593549 -0.64048166 -0.42597818]]


In [6]:
print(data*10)

[[-13.08781558  -3.63791118 -14.96609425]
 [ -9.95935488  -6.40481657  -4.2597818 ]]


In [7]:
print(data + data)

[[-2.61756312 -0.72758224 -2.99321885]
 [-1.99187098 -1.28096331 -0.85195636]]


In [8]:
print(data.shape)
# 维度大小
print(data.dtype)
# 数组数据类型

(2, 3)
float64


In [9]:
# 创建数组最简单的方法就是用array
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
print(arr1)



[6.  7.5 8.  0.  1. ]


In [10]:
# 嵌套序列（由一组等长列表组成的列表）将会被转换成一个多维数组
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print(arr2)




[[1 2 3 4]
 [5 6 7 8]]


In [15]:
# ndim: number of array dimensions就是几行的意思
# array数组
# 注意元组的这个不一样
a1 = np.zeros(((1, 2, 3, 4)))
print(a1.ndim)
print(arr2.ndim)
print(arr2.shape)

4
2
(2, 4)


In [2]:
# 创建全0和全1的数组，还有创建没具体值的数组
print(np.zeros(10))
print(np.zeros((3, 6)))
print(np.empty((2, 3, 2)))
# empty分配内存空间产生随机值，不进行初始化

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[[1.11098724e-311 3.16202013e-322]
  [0.00000000e+000 0.00000000e+000]
  [1.29060531e-306 3.69628970e-033]]

 [[1.86352629e+160 5.79703208e+170]
  [3.44013139e+179 9.84970541e+165]
  [2.65057421e-052 1.50349837e+161]]]


In [3]:
print(np.arange(15))
# 类似range

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [4]:
# numpy关注的是数值计算，所以如果没特别指定的话基本都是float64
# 其他的创建函数自己百度去




In [5]:
# dtype是一个特殊对象，含有ndarray将一块内存解释为特定数据类型所需的信息
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
# 其他的数据类型自己百度去
print(arr1.dtype)
print(arr2.dtype)


float64
int32


In [6]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
# astype来修改数据类型
float_arr = arr.astype(np.float64)
print(float_arr.dtype)
# 如果浮点数转成整数，那么小数部分将会被截取删了

int32
float64


In [7]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
# 这个字符串数组表示的全是数字，那么也可以转成数值形式
print(numeric_strings.astype(float))
# 用这个numpy.string_时候要注意，numpy的字符串数据是大小固定的，发生截取的时候不会警告的

[ 1.25 -9.6  42.  ]


In [8]:
int_array = np.arange(10)
print(int_array)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
print(calibers)
print(int_array.astype(calibers.dtype))
# 这个其实就是给每一个后面加上个小数点，但是没有小数位

[0 1 2 3 4 5 6 7 8 9]
[0.22  0.27  0.357 0.38  0.44  0.5  ]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [9]:
empty_uint32 = np.empty(8, dtype='u4')
# 不一定要写uint32，u4也可以
print(empty_uint32)
print(empty_uint32.dtype)

[2362991368        523 1661424176 1988385690 1324770695      12290
          0  544042868]
uint32


In [10]:
# 数组运算
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

print(arr)
print(arr * arr)
print(arr - arr)



[[1. 2. 3.]
 [4. 5. 6.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [11]:
print(1 / arr)
print(arr ** 0.5)
# 数组里面每一个值都会受影响

[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [12]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
# 进行比较生成的是布尔值的
print(arr2)
print(arr2 > arr)

[[ 0.  4.  1.]
 [ 7.  2. 12.]]
[[False  True False]
 [ True False  True]]


In [13]:
# 两个数组维数不同，元素到元素的操作是不可能的，但是numpy可能，较小的数组会广播道较大数组的大小
# 以便形状可兼容
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([1.0,2.0,3.0])  
print ('第一个数组：')  
print (a) 
print ('\n第二个数组：')  
print (b) 
print ('\n第一个数组加第二个数组：')  
print (a + b)
# 小的数组直接变成了四维的123，都是补的原始值而不是补0

第一个数组：
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]

第二个数组：
[1. 2. 3.]

第一个数组加第二个数组：
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [14]:
# 如果满足以下规则，可以进行广播：
# 
#     ndim较小的数组会在前面追加一个长度为 1 的维度。
#     输出数组的每个维度的大小是输入数组该维度大小的最大值。
#     如果输入在每个维度中的大小与输出大小匹配，或其值正好为 1，则可以在计算中使用该输入。
#     如果输入的某个维度大小为 1，则该维度中的第一个数据元素将用于该维度的所有计算。
# 
# 如果上述规则产生有效结果，并且满足以下条件之一，那么数组被称为可广播的。
# 
#     数组拥有相同形状。
#     数组拥有相同的维数，每个维度拥有相同长度，或者长度为 1。
#     数组拥有极少的维度，可以在其前面追加长度为 1 的维度，使上述条件成立。


In [15]:
arr = np.arange(10)
# 索引和切片
print (arr)
#arr的第6个元素
print (arr[5])
#arr的第6-8个元素，[5:8]左闭右开
print (arr[5:8])

arr[5:8] = 12
# 中间这几个值全都变成了12
print (arr)


[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]
[ 0  1  2  3  4 12 12 12  8  9]


In [ ]:
# 注意这些改的是原始的数组，不会和平时一样需要复制或者深拷贝这些
arr_slice = arr[5:8]
print (arr_slice)
arr_slice[1] = 12345
print (arr)
# 最初的arr也发生了变化
# 要知道np是为了弄大数据的，如果坚持复制来复制去的话会花费很多性能和内存的
# 如果要副本的话就需要明确的用copy来复制

[12 12 12]
[    0     1     2     3     4    12 12345    12     8     9]


In [2]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# 索引
print(arr2d[2])

[7 8 9]


In [3]:
print (arr2d[0][2])
print (arr2d[0, 2])
# 进行递归访问，0的2位置上的元素，这两个方式是一样的

3
3


In [7]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3d)
print("\n")
print(arr3d[0])
# 返回0上维度低一点的ndarray

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


[[1 2 3]
 [4 5 6]]


In [8]:
# 将arr3d[0]的数据进行备份
old_values = arr3d[0].copy()
# 修改arr3d[0]的值为42
arr3d[0] = 42
print(arr3d)
print('===========分割线============')
arr3d[0] = old_values
print(arr3d)
# 标量值和数组都可以被赋值进去

[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]
===========分割线============
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
