In [1]:
import numpy as np

my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [3]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 41.9 ms


In [4]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 1.18 s


In [ ]:
# 可以看出来这个np同样用list所消耗的时间比直接用list要少很多

In [5]:
# 多维数组是ndarray
data = np.random.randn(2, 3)
# 生成二行三列的随机的数组
print(data)




[[-1.30878156 -0.36379112 -1.49660942]
 [-0.99593549 -0.64048166 -0.42597818]]


In [6]:
print(data*10)

[[-13.08781558  -3.63791118 -14.96609425]
 [ -9.95935488  -6.40481657  -4.2597818 ]]


In [7]:
print(data + data)

[[-2.61756312 -0.72758224 -2.99321885]
 [-1.99187098 -1.28096331 -0.85195636]]


In [8]:
print(data.shape)
# 维度大小
print(data.dtype)
# 数组数据类型

(2, 3)
float64


In [9]:
# 创建数组最简单的方法就是用array
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
print(arr1)



[6.  7.5 8.  0.  1. ]


In [10]:
# 嵌套序列（由一组等长列表组成的列表）将会被转换成一个多维数组
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print(arr2)




[[1 2 3 4]
 [5 6 7 8]]


In [15]:
# ndim: number of array dimensions就是几行的意思
# array数组
# 注意元组的这个不一样
a1 = np.zeros(((1, 2, 3, 4)))
print(a1.ndim)
print(arr2.ndim)
print(arr2.shape)

4
2
(2, 4)


In [2]:
# 创建全0和全1的数组，还有创建没具体值的数组
print(np.zeros(10))
print(np.zeros((3, 6)))
print(np.empty((2, 3, 2)))
# empty分配内存空间产生随机值，不进行初始化

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[[1.11098724e-311 3.16202013e-322]
  [0.00000000e+000 0.00000000e+000]
  [1.29060531e-306 3.69628970e-033]]

 [[1.86352629e+160 5.79703208e+170]
  [3.44013139e+179 9.84970541e+165]
  [2.65057421e-052 1.50349837e+161]]]


In [3]:
print(np.arange(15))
# 类似range

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [4]:
# numpy关注的是数值计算，所以如果没特别指定的话基本都是float64
# 其他的创建函数自己百度去




In [5]:
# dtype是一个特殊对象，含有ndarray将一块内存解释为特定数据类型所需的信息
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
# 其他的数据类型自己百度去
print(arr1.dtype)
print(arr2.dtype)


float64
int32


In [6]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
# astype来修改数据类型
float_arr = arr.astype(np.float64)
print(float_arr.dtype)
# 如果浮点数转成整数，那么小数部分将会被截取删了

int32
float64


In [7]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
# 这个字符串数组表示的全是数字，那么也可以转成数值形式
print(numeric_strings.astype(float))
# 用这个numpy.string_时候要注意，numpy的字符串数据是大小固定的，发生截取的时候不会警告的

[ 1.25 -9.6  42.  ]


In [8]:
int_array = np.arange(10)
print(int_array)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
print(calibers)
print(int_array.astype(calibers.dtype))
# 这个其实就是给每一个后面加上个小数点，但是没有小数位

[0 1 2 3 4 5 6 7 8 9]
[0.22  0.27  0.357 0.38  0.44  0.5  ]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [9]:
empty_uint32 = np.empty(8, dtype='u4')
# 不一定要写uint32，u4也可以
print(empty_uint32)
print(empty_uint32.dtype)

[2362991368        523 1661424176 1988385690 1324770695      12290
          0  544042868]
uint32


In [10]:
# 数组运算
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

print(arr)
print(arr * arr)
print(arr - arr)



[[1. 2. 3.]
 [4. 5. 6.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [11]:
print(1 / arr)
print(arr ** 0.5)
# 数组里面每一个值都会受影响

[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [12]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
# 进行比较生成的是布尔值的
print(arr2)
print(arr2 > arr)

[[ 0.  4.  1.]
 [ 7.  2. 12.]]
[[False  True False]
 [ True False  True]]


In [13]:
# 两个数组维数不同，元素到元素的操作是不可能的，但是numpy可能，较小的数组会广播道较大数组的大小
# 以便形状可兼容
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([1.0,2.0,3.0])  
print ('第一个数组：')  
print (a) 
print ('\n第二个数组：')  
print (b) 
print ('\n第一个数组加第二个数组：')  
print (a + b)
# 小的数组直接变成了四维的123，都是补的原始值而不是补0

第一个数组：
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]

第二个数组：
[1. 2. 3.]

第一个数组加第二个数组：
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [14]:
# 如果满足以下规则，可以进行广播：
# 
#     ndim较小的数组会在前面追加一个长度为 1 的维度。
#     输出数组的每个维度的大小是输入数组该维度大小的最大值。
#     如果输入在每个维度中的大小与输出大小匹配，或其值正好为 1，则可以在计算中使用该输入。
#     如果输入的某个维度大小为 1，则该维度中的第一个数据元素将用于该维度的所有计算。
# 
# 如果上述规则产生有效结果，并且满足以下条件之一，那么数组被称为可广播的。
# 
#     数组拥有相同形状。
#     数组拥有相同的维数，每个维度拥有相同长度，或者长度为 1。
#     数组拥有极少的维度，可以在其前面追加长度为 1 的维度，使上述条件成立。


In [15]:
arr = np.arange(10)
# 索引和切片
print (arr)
#arr的第6个元素
print (arr[5])
#arr的第6-8个元素，[5:8]左闭右开
print (arr[5:8])

arr[5:8] = 12
# 中间这几个值全都变成了12
print (arr)


[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]
[ 0  1  2  3  4 12 12 12  8  9]


In [ ]:
# 注意这些改的是原始的数组，不会和平时一样需要复制或者深拷贝这些
arr_slice = arr[5:8]
print (arr_slice)
arr_slice[1] = 12345
print (arr)
# 最初的arr也发生了变化
# 要知道np是为了弄大数据的，如果坚持复制来复制去的话会花费很多性能和内存的
# 如果要副本的话就需要明确的用copy来复制

[12 12 12]
[    0     1     2     3     4    12 12345    12     8     9]


In [2]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# 索引
print(arr2d[2])

[7 8 9]


In [3]:
print (arr2d[0][2])
print (arr2d[0, 2])
# 进行递归访问，0的2位置上的元素，这两个方式是一样的

3
3


In [7]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3d)
print("\n")
print(arr3d[0])
# 返回0上维度低一点的ndarray

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


[[1 2 3]
 [4 5 6]]


In [8]:
# 将arr3d[0]的数据进行备份
old_values = arr3d[0].copy()
# 修改arr3d[0]的值为42
arr3d[0] = 42
print(arr3d)
print('===========分割线============')
arr3d[0] = old_values
print(arr3d)
# 标量值和数组都可以被赋值进去

[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]
===========分割线============
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [9]:
print(arr2d)
print('===========分割线============')
print(arr2d[:2])
# 切0和1轴的

[[1 2 3]
 [4 5 6]
 [7 8 9]]
===========分割线============
[[1 2 3]
 [4 5 6]]


In [10]:
print(arr2d[:2, 1:])
# 后面的是进去之后的从1开始到最后的切

[[2 3]
 [5 6]]


In [12]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

print(names)
print(data)
print(names == 'Bob')
# 这样子来弄个数组索引，用这个里面的true和false对应关系就行了
print(data[names == 'Bob'])

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[ 0.4973647   1.8156115   0.39165585 -0.99502229]
 [-2.00483115  0.01985026  0.66831662 -0.6903029 ]
 [-1.66957736 -0.1975745  -0.42924002  0.00267774]
 [-0.86503121 -0.10477545 -1.23185485  0.68989887]
 [ 1.31805538 -0.20462078  0.84575444  2.59546266]
 [-1.06228126 -1.33718052  1.77527171  0.65031478]
 [ 0.63029048 -0.16200213  0.41393493  0.42105781]]
[ True False False  True False False False]
[[ 0.4973647   1.8156115   0.39165585 -0.99502229]
 [-0.86503121 -0.10477545 -1.23185485  0.68989887]]


In [13]:
print(names != 'Bob')
# 这两种表示否定的方法也都可以
print(data[~(names == 'Bob')])

[False  True  True False  True  True  True]
[[-2.00483115  0.01985026  0.66831662 -0.6903029 ]
 [-1.66957736 -0.1975745  -0.42924002  0.00267774]
 [ 1.31805538 -0.20462078  0.84575444  2.59546266]
 [-1.06228126 -1.33718052  1.77527171  0.65031478]
 [ 0.63029048 -0.16200213  0.41393493  0.42105781]]


In [14]:
cond = names == 'Bob'
print(data[~cond])
# 这样子以后也可以操作这个判定条件了

[[-2.00483115  0.01985026  0.66831662 -0.6903029 ]
 [-1.66957736 -0.1975745  -0.42924002  0.00267774]
 [ 1.31805538 -0.20462078  0.84575444  2.59546266]
 [-1.06228126 -1.33718052  1.77527171  0.65031478]
 [ 0.63029048 -0.16200213  0.41393493  0.42105781]]


In [15]:
# 花式索引：利用整数数组进行索引
arr = np.empty((8, 4))
for i in range(8):
  arr[i] = i
print (arr)



[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


In [16]:
print (arr[[4, 3, 0, 6]])
# 特定顺序来选取子集，这个是位置，不是值

[[4. 4. 4. 4.]
 [3. 3. 3. 3.]
 [0. 0. 0. 0.]
 [6. 6. 6. 6.]]


In [17]:
print(arr[[-3, -5, -7]])

[[5. 5. 5. 5.]
 [3. 3. 3. 3.]
 [1. 1. 1. 1.]]


In [18]:
arr = np.arange(32).reshape((8, 4))
print(arr)
print(arr[[1, 5, 7, 2], [0, 3, 1, 2]])
# 传入多个也可以，里面也是通过对应位置来的，返回的是一维数组，里面都是值

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[ 4 23 29 10]


In [19]:
# 要想变成常见的矩阵区域的话
print(arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]])

# 要花式索引和切片不一样，它是将数据复制到新的数组中，切片是直接在原数组上进行切片


[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


In [20]:
arr = np.arange(15).reshape((3, 5))
print(arr)
print(arr.T)
# 简单的转置操作

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [21]:
arr = np.random.randn(6, 3)
print (arr)
print (np.dot(arr.T, arr))
# np.dot计算矩阵内积

[[ 0.27447302 -0.8221905  -1.09027535]
 [ 0.58485829 -0.50854391 -1.88884074]
 [ 0.26296954 -1.80796589 -0.10604938]
 [-0.45421317  0.68486192 -1.58439948]
 [ 0.99067653  0.69480679  1.78158736]
 [ 1.12546943 -0.71632794  3.0177793 ]]
[[ 2.94097868 -1.42748492  4.44920718]
 [-1.42748492  5.66827284  0.03975064]
 [ 4.44920718  0.03975064 19.55903327]]


In [22]:
arr = np.arange(16).reshape((2, 2, 4))
print(arr)
print('==========分割线==============')
print(arr.transpose((1, 0, 2)))
# 高维数组转置就需要用这个了，当然这个的话需要得到一个由轴编号组成的元组才能进行转置操作
# 这个实际上就是1和2的位置进行了互换，想成ABCD来看就是了

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
==========分割线==============
[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]


In [23]:
print(arr)
print('==========分割线==============')
print(arr.swapaxes(1, 2))
# 这个就是另外一种全部都转置了，但是也是1和2的位置互换

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
==========分割线==============
[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]


In [24]:
arr = np.arange(10)

print(arr)
# 这两个都是通用函数，对数据执行元素级运算
print(np.sqrt(arr))
# 开方
print(np.exp(arr))
# e =2.71828...这个exp（3）就是e的三次方

[0 1 2 3 4 5 6 7 8 9]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]


In [25]:
x = np.random.randn(8)
y = np.random.randn(8)

print(x)
print(y)
print(np.maximum(x, y))

[0.68725904 0.29853095 0.24848817 0.36633978 0.54712715 0.11145256
 0.14068004 0.57720423]
[ 0.39557314  0.18432082  0.4906254   0.23255789 -1.0968044  -0.18188899
 -0.43622292  0.44166738]
[0.68725904 0.29853095 0.4906254  0.36633978 0.54712715 0.11145256
 0.14068004 0.57720423]
